Monica mooney
borisv1307/Dungeon-Crawler-Fall-2022-Drexel pull request #50
Opened 2022-12-01 04:56 UTC by monmooney5523

First PR for Final Project.

Please provide any comments / feedback you feel is necessary! Thanks in advance.

2022-12-01 17:02 UTC, borisv1307 commented
All checks have failed.

2022-12-03 01:15 UTC, monmooney5523 commented
> All checks have failed.

Updated the use of Random to instead use SecureRandom(). Also updated the time between random object generation and refactored code. 

All tests are passing, final submission.

2022-12-03 15:40 UTC, borisv1307 requested changes

2022-12-03 15:40 UTC, borisv1307 commented on src/main/java/wrappers/RandomWrapper.java
> +            return null;
NEVER RETURN NULL
Never allow null
Throw a new exception if you have to.

2022-12-03 21:25 UTC, borisv1307 requested changes

2022-12-03 21:25 UTC, borisv1307 commented on src/main/java/engine/GameEngine.java
>          if (collectableObjects != null) {
Remove this check and redesign to make sure it's never null.
Initialize it to an empty list in the constructor, for example.

2022-12-07 21:34 UTC, closed without merging