Changes added to SRC Main.
borisv1307/Dungeon-Crawler-Fall-2022-Drexel pull request #68
Opened 2022-12-07 22:29 UTC by jmadde882

Enemies in red have been added.

UI text box has been added.

2022-12-07 22:46 UTC, borisv1307 commented
Please remove the .idea folder and all files. Those shouldn't go into git.

2022-12-09 00:44 UTC, borisv1307 requested changes

2022-12-09 01:14 UTC, jmadde882 commented
Okay I’ll adjust that tomorrow. Are you able to run the game and see the enemy movement?
________________________________
From: borisv1307 ***@***.***>
Sent: Thursday, December 8, 2022 7:44:35 PM
To: borisv1307/Dungeon-Crawler-Fall-2022-Drexel ***@***.***>
Cc: Madden, Jack ***@***.***>; Author ***@***.***>
Subject: Re: [borisv1307/Dungeon-Crawler-Fall-2022-Drexel] Changes added to SRC Main. (PR #68)


@borisv1307 requested changes on this pull request.

________________________________

In src/main/java/engine/GameEngine.java<https://urldefense.com/v3/__https://github.com/borisv1307/Dungeon-Crawler-Fall-2022-Drexel/pull/68*discussion_r1043955867__;Iw!!CQl3mcHX2A!Fa-7i1PXLLTQjNtKgjmheqTqgZJuHvIM_KbkTT6d6LHxIlRjfkXhc28tk43dJMm5ySMzsEUKghrr2SKwgLSBq8F_SIcY$>:

> +                System.exit(0);
+            }
+        }
+
+        randomPosition();
+    }
+
+    public boolean isExit() {
+        return exit;
+    }
+
+    public void setExit(boolean exit) {
+        this.exit = exit;
+    }
+
+    public boolean setEnemyCount(int count) {


This whole method was not TDD'd. Please delete the whole method and actually slowly TDD it. Every small thing, 1 small test.

________________________________

In src/main/java/engine/GameEngine.java<https://urldefense.com/v3/__https://github.com/borisv1307/Dungeon-Crawler-Fall-2022-Drexel/pull/68*discussion_r1043956101__;Iw!!CQl3mcHX2A!Fa-7i1PXLLTQjNtKgjmheqTqgZJuHvIM_KbkTT6d6LHxIlRjfkXhc28tk43dJMm5ySMzsEUKghrr2SKwgLSBq_lE-6AH$>:

> +        int x;
+        int y;
+        TileType type;
+
+        enemies.clear();
+
+        SecureRandom random = new SecureRandom();
+
+        int enemycount = 0;
+        for (int i = 0; i < count; i++) {
+            while (!created) {
+                x = (int) Math.round(random.nextDouble()) * width;
+                y = (int) Math.round(random.nextDouble()) * height;
+                type = tiles.get(new Point(x, y));
+
+                if (type == TileType.PASSABLE && !((x == 0 || x == 1) && (y == 0 || y == 1))) {


Unclean. Extract everything within the () to its own human readable method and a bunch of tests to make sure that logic works.

________________________________

In src/main/java/engine/GameEngine.java<https://urldefense.com/v3/__https://github.com/borisv1307/Dungeon-Crawler-Fall-2022-Drexel/pull/68*discussion_r1043956312__;Iw!!CQl3mcHX2A!Fa-7i1PXLLTQjNtKgjmheqTqgZJuHvIM_KbkTT6d6LHxIlRjfkXhc28tk43dJMm5ySMzsEUKghrr2SKwgLSBqxDfByYV$>:

> +    }
+
+    public boolean setEnemyCount(int count) {
+
+        boolean created = false;
+
+        int width = getLevelHorizontalDimension();
+        int height = getLevelVerticalDimension();
+
+        int x;
+        int y;
+        TileType type;
+
+        enemies.clear();
+
+        SecureRandom random = new SecureRandom();


Random should be wrapped and mocked.

________________________________

In src/main/java/engine/GameEngine.java<https://urldefense.com/v3/__https://github.com/borisv1307/Dungeon-Crawler-Fall-2022-Drexel/pull/68*discussion_r1043956637__;Iw!!CQl3mcHX2A!Fa-7i1PXLLTQjNtKgjmheqTqgZJuHvIM_KbkTT6d6LHxIlRjfkXhc28tk43dJMm5ySMzsEUKghrr2SKwgLSBq9Q5muju$>:

> +
+        boolean created = false;
+
+        int width = getLevelHorizontalDimension();
+        int height = getLevelVerticalDimension();
+
+        int x;
+        int y;
+        TileType type;
+
+        enemies.clear();
+
+        SecureRandom random = new SecureRandom();
+
+        int enemycount = 0;
+        for (int i = 0; i < count; i++) {


You have a while inside of an if. Refactor this when you recreate this method. Decouple your logic. Create more small methods that are each individually tested.

________________________________

In src/main/java/engine/GameEngine.java<https://urldefense.com/v3/__https://github.com/borisv1307/Dungeon-Crawler-Fall-2022-Drexel/pull/68*discussion_r1043956897__;Iw!!CQl3mcHX2A!Fa-7i1PXLLTQjNtKgjmheqTqgZJuHvIM_KbkTT6d6LHxIlRjfkXhc28tk43dJMm5ySMzsEUKghrr2SKwgLSBq8sNPIoD$>:

> +                if (type == TileType.PASSABLE && !((x == 0 || x == 1) && (y == 0 || y == 1))) {
+                    Point pt = new Point(x, y);
+                    tiles.put(pt, TileType.ENEMY);
+                    created = true;
+                    enemies.add(pt);
+                    enemycount++;
+                }
+            }
+
+            created = false;
+        }
+
+        return enemycount > 0;
+    }
+
+    public int randomPosition() {


Same feedback (pretty much all of it) as the method above.

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/borisv1307/Dungeon-Crawler-Fall-2022-Drexel/pull/68*pullrequestreview-1210960431__;Iw!!CQl3mcHX2A!Fa-7i1PXLLTQjNtKgjmheqTqgZJuHvIM_KbkTT6d6LHxIlRjfkXhc28tk43dJMm5ySMzsEUKghrr2SKwgLSBqwaMOYvD$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/A2FMXRQIKGFBGCGVZJ6W75DWMJ6HHANCNFSM6AAAAAASXMDKEY__;!!CQl3mcHX2A!Fa-7i1PXLLTQjNtKgjmheqTqgZJuHvIM_KbkTT6d6LHxIlRjfkXhc28tk43dJMm5ySMzsEUKghrr2SKwgLSBq_NwL-ug$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-12-09 22:42 UTC, jmadde882 commented on src/main/java/engine/GameEngine.java
> +    public boolean setEnemyCount(int count) {
adressed

2022-12-09 22:42 UTC, jmadde882 commented on src/main/java/engine/GameEngine.java
> +                if (type == TileType.PASSABLE && !((x == 0 || x == 1) && (y == 0 || y == 1))) {
fixed

2022-12-09 22:43 UTC, jmadde882 commented on src/main/java/engine/GameEngine.java
> +        for (int i = 0; i < count; i++) {
fixed

2022-12-09 22:43 UTC, jmadde882 commented on src/main/java/engine/GameEngine.java
> +    public int randomPosition() {
fixed

2022-12-09 23:30 UTC, jmadde882 commented on src/main/java/engine/GameEngine.java
> +    public int randomPosition() {
fixed

2022-12-12 00:48 UTC, closed without merging